/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_appsync_graphqlEndpoint": "https://qf2bjn3cbrefton7n7vple6l5e.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-j5ymrnchmjaxhesdhnqpddx3y4",
    "aws_cognito_identity_pool_id": "ap-northeast-2:107f6fc3-0c46-4aec-8141-b568808a4de8",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_pFuKNkm89",
    "aws_user_pools_web_client_id": "1e4h9mt0ft4hrgcdukvda69tnh",
    "oauth": {},
    "aws_user_files_s3_bucket": "lecture113543-staging",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
